import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'


export default function Home() {
  const [data, setData] = useState() 
  useEffect(()=>{
  
    const test = fetch('https://jsonplaceholder.typicode.com/photos')
    .then(response => response.json())
    .then(json =>setData(json))
    .catch((err)=>{
      console.log("Error in api ", err)
    })
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div style={{display:'flex', alignItems:"center",justifyContent:"center"}}>
      <h1>Hello India!</h1>
      <p>{JSON.stringify(data[0])}</p>
     </div>
    </div>
  )
}
